// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8VtVP5d88uwIARINQh8BFH2ydM_2lgiM',
    appId: '1:21924730097:web:1264bdb7eb8ab4adaf0550',
    messagingSenderId: '21924730097',
    projectId: 'flutterfire-sabikrahat',
    authDomain: 'flutterfire-sabikrahat.firebaseapp.com',
    storageBucket: 'flutterfire-sabikrahat.appspot.com',
    measurementId: 'G-6T2C6CCNB2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqAf_xpRpnJ4_ZDQQGJReyCD8sST_c5-Q',
    appId: '1:21924730097:android:c703aaa9e66b241faf0550',
    messagingSenderId: '21924730097',
    projectId: 'flutterfire-sabikrahat',
    storageBucket: 'flutterfire-sabikrahat.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_97l0Qb79OnF8oAppRLjR6O64Fo3Lh8o',
    appId: '1:21924730097:ios:bf10b3c8b9fae4a5af0550',
    messagingSenderId: '21924730097',
    projectId: 'flutterfire-sabikrahat',
    storageBucket: 'flutterfire-sabikrahat.appspot.com',
    iosBundleId: 'com.sabikrahat.flutterfirePlayground',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_97l0Qb79OnF8oAppRLjR6O64Fo3Lh8o',
    appId: '1:21924730097:ios:642db748355f63f9af0550',
    messagingSenderId: '21924730097',
    projectId: 'flutterfire-sabikrahat',
    storageBucket: 'flutterfire-sabikrahat.appspot.com',
    iosBundleId: 'com.sabikrahat.flutterfirePlayground.RunnerTests',
  );
}
